theme: jekyll-theme-minimal

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

title: firg.xyz
description: What's new again is old.

logo: assets/img/mylogo.png